### ISSUE TITLE
Support batch operations

### ISSUE THREAD

**Issue by Xazax-hun** [mikebmcl/P0267_RefImpl#67]
It might be good to have APIs to support batch operations such as building a path from a collection of points.

**Comment by mikebmcl** [comment]
There are several ways to do this. As of now, the `basic_interpreted_path` class template has ctor overloads that take a `basic_path_builder` class template object, a pair of `ForwardIterator`, and an initializer list of figure items. So one option is to use the initializer list ctor overload. The remaining options are to create a sequential container of some sort and add items in batch using its `initializer_list` ctor or its `insert` member function overload that takes an `initializer_list`.

Note that a `std::array` can be used with the ForwardIterator ctor. Other ctors are certainly possible, but the best I can promise is to try to look at it in the future. If you think it should be pursued, please file it as an issue against the io2dts repo since it would be initially be an API design issue rather than a reference implementation issue.

With the recent switch to a requirements-based design, there is a lot of work to be done to modify P0267 to match the new design. I do think this is something worth investigating, but as its a feature addition request, our first priority is to modify the proposal to match the design changes that are intended for R7 (the next revision of P0267).

Please do create an issue on io2dts. I can't promise anything more than that we'll consider it after we finish these high priority revisions, but it's something I'd be willing to investigate a bit once those revisions are done, so long as you feel that it's worth pursuing.

Best regards,

-Mike
